### PR TITLE
in memory kafka support

### PR DESCRIPTION
**Pull request by patrickleet**
feat: support kafka by keeping track of previously acked messages from batch in store - MemoryStore only so far

need to implement RedisStore

### CODE REVIEW

**Comment by patrickleet** [comment]
@mateodelnorte got this working a bit differently for kafka, but pretty similar. Wanna take a quick look?

Don't want to merge it until we split up sb though and servicebus-kafka is published.

**Comment by patrickleet** [comment]
it's using the store to keep track of acks

**Comment by patrickleet** [comment]
and obv need redis implementation of that if that seems logical to you

**Comment by patrickleet** [comment]
@mateodelnorte should servicebus-retry for kafka be a separate package? what do you think of this?

**Comment by mateodelnorte** [comment]
If there are no dependencies required, and tests pass for both rmq and Kafka, I'd say there's no need to separate.

**Pull request closed without merging**
